/**
 * Secrets are deliberately absent from wrangler.jsonc so they can never be
 * committed. Declaring them here merges into the `Env` interface generated by
 * `npm run cf-typegen` (worker-configuration.d.ts).
 */
interface Env {
	/** 32-byte base64 key used to encrypt upstream credentials at rest. */
	CREDENTIAL_ENCRYPTION_KEY: string;
}
