/**
 * Domain types and shared constants.
 *
 * The `Env` interface is generated by `npm run cf-typegen` (see
 * worker-configuration.d.ts); secrets are added in src/env.d.ts.
 */

/** Date-versioned API surface. Stamped on every response and in the OpenAPI spec. */
export const API_VERSION = '2026-09-13';

/** Visible prefix on minted API keys, so a leaked-looking string is recognisable. */
export const KEY_PREFIX = 'muse_';

export type Access = 'none' | 'read' | 'write';

export const ACCESS_RANK: Record<Access, number> = { none: 0, read: 1, write: 2 };

export function minAccess(a: Access, b: Access): Access {
	return ACCESS_RANK[a] <= ACCESS_RANK[b] ? a : b;
}

export function isAccess(value: unknown): value is Access {
	return value === 'none' || value === 'read' || value === 'write';
}

/** Access levels a key grant may carry. 'none' is expressed by omitting the grant. */
export function isGrantAccess(value: unknown): value is Exclude<Access, 'none'> {
	return value === 'read' || value === 'write';
}

export interface Account {
	id: string;
	username: string;
	passwordHash: string;
	isAdmin: boolean;
	createdAt: number;
	disabledAt: number | null;
	failedLogins: number;
	lockedUntil: number | null;
}

export interface Session {
	id: string;
	tokenHash: string;
	accountId: string;
	createdAt: number;
	expiresAt: number;
	userAgent: string | null;
}

export interface Connection {
	id: string;
	accountId: string;
	provider: string;
	label: string;
	authType: string;
	/** Null for token-only auth types. */
	username: string | null;
	/** AES-GCM blob: `v1:<iv_b64>:<ciphertext_b64>`. Never leaves the Worker. */
	secretCiphertext: string;
	/** Masked tail of the secret, for the console to identify a credential. */
	secretHint: string;
	/** Provider-owned configuration. The core never interprets it. */
	configJson: string;
	/** unverified | ok | error */
	status: string;
	lastError: string | null;
	createdAt: number;
	updatedAt: number;
}

export interface ConnectionResource {
	id: string;
	connectionId: string;
	/** Opaque to the core; the provider decides what a resource key means. */
	resourceKey: string;
	/** calendar | addressbook | provider-defined */
	kind: string;
	displayName: string | null;
	maxAccess: Access;
	metaJson: string;
	discoveredAt: number;
}

export interface ApiKey {
	id: string;
	accountId: string;
	name: string;
	prefix: string;
	tokenHash: string;
	createdAt: number;
	expiresAt: number | null;
	lastUsedAt: number | null;
}

export interface ApiKeyGrant {
	id: string;
	keyId: string;
	connectionId: string;
	/** A specific collection key, or '*' for every collection the connection allows. */
	resourceKey: string;
	maxAccess: Exclude<Access, 'none'>;
}

export type NoticeSeverity = 'info' | 'warning' | 'critical';

export interface Notice {
	id: string;
	accountId: string;
	kind: string;
	severity: NoticeSeverity;
	title: string;
	body: string;
	connectionId: string | null;
	resourceKey: string | null;
	metaJson: string;
	createdAt: number;
}

/** A resource (collection or equivalent) a provider exposes for scoping. */
export interface DiscoveredResource {
	/** Opaque to the core; the provider decides what a resource key means. */
	resourceKey: string;
	kind: string;
	displayName: string;
	meta?: Record<string, unknown>;
}

/** Resolved identity for an agent request. */
export interface AgentIdentity {
	key: ApiKey;
	account: Account;
}

/** Resolved identity for a frontend request. */
export interface SessionIdentity {
	account: Account;
	session: Session;
}
